name: Lint & Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn config set ignore-engines true
      - run: yarn install --frozen-lockfile --ignore-engines
      - run: yarn lint
      - run: yarn build
